name: Mergestat Release

on:
  push:
    branches:
      - "release/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push ui
      uses: docker/build-push-action@v5
      with:
        context: "./ui"
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-console:${{ github.ref_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-console:latest

    - name: Build and push graphql
      uses: docker/build-push-action@v5
      with:
        context: "./graphql"
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-graphql:${{ github.ref_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-graphql:latest

    - name: Build and push ui
      uses: docker/build-push-action@v5
      with:
        context: "."
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-worker:${{ github.ref_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-worker:latest